#!/bin/sh
#
# Runs `npm run test` and doesn't push if a test fails.

set -e

echo 'Testing...'

# Add `test` to `scripts` in `package.json` with appropriate options
# from your testing framework.  E.g. for mocha:
#
#   `"test": "mocha --bail"`
#
npm test

echo 'Committing...'
