#!/bin/sh
#
# ~/.config/openbox/autostart
#
# This script is run by 'openbox-session'

# TODO: Add volume, brightness and wifi widgets

: "${BATDIR:=/sys/class/power_supply/BAT1}"
export BATDIR

# <date> <battery_info>
/usr/bin/xterm \
	-title 'Statusbar' \
	-fg navajowhite1 \
	+bc \
	+sb \
	-cr rgb:10/10/10 \
	-geometry 56x1+0+0 \
	-e sh -c '
		while sleep 1
		do
			read -r stat <"$BATDIR/status"
		        read -r cap <"$BATDIR/capacity"
			vol=$(
				amixer get Master |
				awk "/Front Left:/{print \$5}"
			)
			if test $((blink)) -eq 1
			then
				blink=0
				case $stat in
				Discharging)
					test "$cap" -lt 20 &&
					printf "\\033[01;41;37m" ;;
				Charging|Full)
					test "$cap" -gt 80 &&
					printf "\\033[01;42;37m" ;;
				esac
			else
				blink=1
				printf "\\033[0m"
			fi
			printf "\\n%s\\t%s: %s%% %s" \
				"$(date)" "$stat" "$cap" "$vol"
		done
	'
