# ~/.tmux.conf

set -g default-command "${SHELL}"  # No login shell (default "-${SHELL}")
set -g escape-time 10  # Stop laggy <Esc> in vi
#set -g status off
set -g set-titles on  # Set pane title with '\033[2; ... \007'
set -g allow-rename on  # Set window title with '\033k ... \033\\'
