#!/bin/sh

main() {
    case "$1" in
        -f|--force)
            shift
            ln() {
                command ln -f "$@"
            }
    esac

    ln -s "$PWD/bash/bashrc" ~/.bashrc

    test -d ~/.local/bin/ || mkdir ~/.local/bin

    for x in "$PWD"/bin/*; do
        ln -s "$x" ~/.local/bin/
    done

    for dir in git tmux vim VSCodium; do
        ln -s "$PWD/$dir" ~/.config/
    done
}

main "$@"
