#!/bin/sh

configs='
bash
git
readline
tmux
vim
VSCodium
'

create_symlink() {
    # $1: full path to file
    # $2: full path to link
    ln -s "$1" "$2" && echo "symlinked ~${1#"$HOME"} -> ~${2#"$HOME"}"
}

remove_symlink() {
    if test -h "$1"; then
        rm "$1" && echo "removed symlink ~${1#"$HOME"}"
    fi
}

install_config() {
    for c in $configs; do
        create_symlink "$PWD/$c" "$HOME/.config/$c"
    done
}

uninstall_config() {
    for c in $configs; do
        remove_symlink "$HOME/.config/$c"
    done
}

install_bin() {
    test -d ~/.local/bin || mkdir ~/.local/bin

    for f in bin/*; do
        create_symlink "$PWD/$f" "$HOME/.local/$f"
    done
}

uninstall_bin() {
    for f in bin/*; do
        remove_symlink "$HOME/.local/$f"
    done
}

install_lib() {
    test -d ~/.local/lib || mkdir -p ~/.local/lib

    for d in lib/*; do
        create_symlink "$PWD/$d" "$HOME/.local/$d"
    done
}

uninstall_lib() {
    for d in lib/*; do
        remove_symlink "$HOME/.local/$d"
    done
}

uninstall() {
    remove_symlink ~/.bashrc

    uninstall_config
    uninstall_bin
    uninstall_lib
}

install() {
    create_symlink "$PWD/bash/bashrc" ~/.bashrc

    install_config
    install_bin
    install_lib
}

main() {
    case $1 in
        '')
            ;;
        -f | --force)
            shift
            ln() {
                command ln -f "$@"
            }
            ;;
        -u | --uninstall)
            cmd=uninstall
            ;;
        -r | --reinstall)
            uninstall
            ;;
        *)
            echo "Usage: ./install [-f|--force]" >&2
            echo "       ./install [-u|--uninstall]" >&2
            exit 1
    esac

    "${cmd:-install}"
}

main "$@"
