" TODO: Get byte offset of a given line + column position.
" For use in 'formatexpr' to save and restore cursor position when formatting,
" or to format only a section of the buffer, specified by a range of
" byte-offsets (e.g. with `prettier`)
" Look at: `:h line2byte()`, `:h col()`

set autoindent
set backupdir=~/.config/vim/backups,.
set formatoptions+=j    " Remove comment leader when joining lines.
set hidden
set listchars=tab:⇥\ ,trail:·
set nohlsearch
set noincsearch
set noruler
set noshowmode
set statusline=%f\ %r%m%=%y
set scrolloff=0
set shiftwidth=0    " 'shiftwidth' follows 'tabstop'.
set shortmess=aoOsTcC
set titleold=
set title
set titlestring=%f%{%&ft=='help'?'\ (help)':'\ %m%h'%}\ -\ VIM%{mode()=='i'?'\ (insert)':''}
set wildmode=longest,list

filetype plugin indent on

autocmd FileType vim,html,css,javascript set ts=2 et
autocmd FileType vim,sh,bash,zsh,python set ts=4 et

if $TERMINAL_THEME == 'solarized'
    colorscheme solarized
else
    colorscheme vs
endif

packadd! editorconfig    " Read .editorconfig files.
packadd! comment    " Comment code with `gc{motion}`.

" Highlight trailing whitespace.
" https://vim.fandom.com/wiki/Highlight_unwanted_spaces
3match Error /\s\+$/
autocmd BufWinEnter * 3match Error /\s\+$/
autocmd InsertEnter * 3match Error /\s\+\%#\@<!$/
autocmd InsertLeave * 3match Error /\s\+$/

" Make Ctrl-Backspace delete the previous word.
inoremap <C-H> <C-W>
cnoremap <C-H> <C-W>

" <Esc> in command line opens editing window.
cnoremap <Esc> <C-F>

" Emulate readline tab completion.
" https://medium.com/@sszreter/vim-tab-autocomplete-in-insert-mode-and-fuzzy-search-for-opening-files-484260f52618
function! InsertTabWrapper()
    let col = col('.') - 1
    " If the cursor is at the start of the line or the char behind the cursor is
    " not a keyword character.
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<Tab>"
    else
        return "\<C-P>"
    endif
endfunction
inoremap <expr> <Tab> InsertTabWrapper()

" Get syntax group under cursor with `gs`.
function! SynStack()
    if !exists("*synstack")
        return
    endif
    echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
nnoremap gs :call SynStack()<CR>
