#!/bin/sh
#
# Exits with non-zero status if any staged file has trailing whitespace.
#
# XXX: This script will break if filenames contain whitespace.
# XXX: This script also does not work properly.
#
set -e

staged_files=$(git diff --staged --name-only)

files_with_trailing_whitespace=$(grep -n '^[[:space:]][[:space:]]*$' $staged_files)

if test -n "$files_with_trailing_whitespace"
then
	echo "whitespace errors found, aborting commit" >&2
	printf '%\n' $files_with_trailing_whitespace
	exit 1
fi

exit 0
