#!/bin/sh
#
# Exits with non-zero status if any staged file has trailing whitespace.

set -e
set --

while IFS= read -r file
do
	grep -q '[[:space:]][[:space:]]*$' "$file" && set -- "$@" "$file"
done <<-EOF
	$(git diff --staged --name-only)
EOF

if test $# -gt 0
then
	echo "whitespace errors found, aborting commit" >&2
	printf '%\n' $files_with_trailing_whitespace
	exit 1
fi

exit 0
