#!/bin/sh
#
# Exits with non-zero status if any staged file has trailing whitespace.

main() {
	set -e
	set -- $(git grep --cached --files-with-matches \
			'[[:space:]][[:space:]]*$')

	if test $# -gt 0
	then
		echo "whitespace errors found, aborting commit" >&2
		printf '%s\n' "$@"
		return 1
	fi

	return 0
}

main "$@"
