# Do nothing if not interactive.
if [[ $- != *i* ]]; then
    return
fi

# Source system defaults if they exist.
if [[ -f /etc/bashrc ]]; then
    . /etc/bashrc
fi


# Shell variables (local to shell; not exported)

PS1='\$ '
PROMPT_COMMAND='__prompt_command'
if [[ $TERM_PROGRAM == 'vscode' ]]; then
    PS1='\w \$ '
    unset PROMPT_COMMAND
fi
CDPATH=.:~:~/.config:~/Projects
HISTFILESIZE=1000000
HISTSIZE=10000
HISTIGNORE='[fb]g*:%*'
HISTCONTROL=ignoreboth


# Environment variables (global; exported to subprocesses)

export BIN=~/.local/bin
if [[ -d $BIN && $PATH != $BIN:* ]]; then
    export PATH=$BIN:$PATH
fi
export LIB=~/.local/lib/
export GIT_HOOKS=~/.config/git/hooks
export TERMINAL_THEMES_DIR=~/.config/bash/themes
: "${TMP=${TEMP:=/tmp}}"
export TMP TEMP
export EDITOR='vi'
export EXINIT='set nocp tm=10 ul=0 bs= ai ci sw=0 hidden cpo+=n backup backupdir=~/.config/vim/backups,.,~/ nosmd noru hl=8r,~i,@b,dn,eb,mb,Mb,nb,rb,sr,Ss,tn,cr,vr,wb,Wn,+r,=n | map!  '
export LESSOPEN='||/usr/bin/lesspipe.sh %s'
export NPM_CONFIG_PREFIX=~/.local
export GOPATH=~/.local


# Shell options

shopt -s globstar                # Allow recursive globbing with '**'.
shopt -s extglob                 # Allow extended pattern matching.
shopt -s histappend              # Append to history file, don't overwrite.
shopt -s lithist                 # Preserve formatting of multiline commands in history.
shopt -s no_empty_cmd_completion # Don't try to complete empty lines.
shopt -s checkjobs               # Warn about background jobs when exiting the shell.


# TTY options

stty -ixon # Disable Ctrl-S pausing input.


# Readline options

# If not running in VSCode or a JetBrains IDE.
if [[ -z $TERM_PROGRAM && -z $TERMINAL_EMULATOR ]]; then
    set -o vi
    bind '"\C-h": backward-kill-word' # Ctrl-Backspace.
fi


# Shell aliases

alias ls='ls --color'
alias grep='grep --color'
alias diff='diff --color'
alias tree='tree --gitignore'
alias open='xdg-open'
alias sh='PS1=sh\$\  sh'
alias dash='PS1=dash\$\  dash'
alias p='printf "%s\\n"'
alias args='i=0 ; for _ ; do printf "%4d %s\\n" $((++i)) "$_" ; done ; unset i'
if [[ $TERM_PROGRAM == 'vscode' ]] && command -v codium &>/dev/null; then
    alias code=codium
fi
if [[ $OS == 'Windows_NT' ]]; then
    alias python='winpty python'
    alias node='winpty node'
    alias gh='winpty gh'
    alias open='explorer'
fi


# Shell functions

# Source library functions.
if [[ -r ~/.local/lib/sh/termctl.sh ]]; then
    . ~/.local/lib/sh/termctl.sh
fi

# Usage: PROMPT_COMMAND='__prompt_command'
#
# Sets terminal title - e.g. `jfox@fedora:~/.config/bash (master)`.
#
__prompt_command() {
    printf '\e]0;%s\a' "${USER}@${HOSTNAME}:${PWD//$HOME/\~}$(__git_ps1)"
}

# Usage: PS1='\w$(__git_ps1)\$ '
#
# A much simplified (and much quicker) version of the prompt which ships
# with `git`.
#
__git_ps1() {
    if ! git status -s &>/dev/null; then
        return
    fi
    local current=$(git branch --show-current)
    if [[ -z $current ]]; then
        current=$(git rev-parse --short HEAD)
    fi
    printf ' (%s)' "$current"
}

# Usage: exec <command>
#
# Only exec <command> if there are no background jobs running.
#
exec() {
    if [[ -n $(jobs) ]]; then
        echo 'cannot exec: background jobs running' >&2
        jobs
        return 1
    fi
    builtin exec "$@"
}
